#!/bin/sh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="sudo $command"
done; unset command

# Navigation up
alias \
        ..="cd .."  \
        .2="cd ../.." \
        .3="cd ../../.." \
        .4="cd ../../../.." \
        .5="cd ../../../.."

# vim and emacs
alias \
        vim="nvim" \
        em="/usr/bin/emacs -nw" \
        emacs="emacsclient -c -a 'emacs'" \
        doomsync="~/.emacs.d/bin/doom sync" \
        doomdoctor="~/.emacs.d/bin/doom doctor" \
        doomupgrade="~/.emacs.d/bin/doom upgrade" \
        doompurge="~/.emacs.d/bin/doom purge"

# Changing ls
alias \
        ls="ls -h --color=auto --group-directories-first" \
        la="ls -Ah --color=auto --group-directories-first" \
        ll="ls -hl --color=auto --group-directories-first" \
        l.="exa -a | egrep '^\.'" \
        els="exa --icons --color=always --group-directories-first" \
        ela="exa -a --icons --color=always --group-directories-first" \
        lt="exa -aT --level=2 --color=always --group-directories-first"
        # lt="ls -R" \

# pacman and yay
alias \
        psyu="sudo pacman -Syu" \
        psyyu="sudo pacman -Syyu" \
        yaysua="yay -Sua --noconfirm" \
        yaysyu="yay -Syu --noconfirm" \
        parsua="paru -Sua --noconfirm" \
        parsyu="paru -Syu --noconfirm" \
        unlock="sudo rm /var/lib/pacman/db.lck" \
        cleanup="sudo pacman -Rns (pacman -Qtdq)"

# get fastest mirrors
alias \
        mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" \
        mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist" \
        mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist" \
        mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize output
alias \
        grep="grep --color=auto" \
        egrep="egrep --color=auto" \
        fgrep="fgrep --color=auto" \
        pacman="pacman --color always" \
        ip="ip -color=always"

# confirm before overwriting something
# alias \
#         cp="cp -i" \
#         mv="mv -i" \
#         rm="rm -i"

# Adding flags
alias \
        df="df -h" \
        free="free -m" \
        lynx="lynx -cfg=~/.lynx/lynx.cfg -lss=~/.lynx/lynx.lss -vikeys" \
        ncmpcpp="ncmpcpp ncmpcpp_directory=$HOME/.config/ncmpcpp/" \
        mocp="mocp -M ~/.config/moc -O MOCDir=~/.config/moc"
        # mocp="mocp -M "$XDG_CONFIG_HOME"/moc -O MOCDir="$XDG_CONFIG_HOME"/moc"

# ps
alias \
        psa="ps auxf" \
        psgrep="ps aux | grep -v grep | grep -i -e VSZ -e" \
        psmem="ps auxf | sort -nr -k 4" \
        pscpu="ps auxf | sort -nr -k 3"

# git
alias \
        add="git add" \
        addup="git add -u" \
        addall="git add ." \
        branch="git branch" \
        checkout="git checkout" \
        clone="git clone" \
        commit="git commit -m" \
        fetch="git fetch" \
        pull="git pull origin" \
        push="git push origin" \
        stat="git status" \
        newtag="git tag -a"
        # tag="git tag" \

# yt-dlp
alias \
        yta-aac="yt-dlp --extract-audio --audio-format aac " \
        yta-best="yt-dlp --extract-audio --audio-format best " \
        yta-flac="yt-dlp --extract-audio --audio-format flac " \
        yta-m4a="yt-dlp --extract-audio --audio-format m4a " \
        yta-mp3="yt-dlp --extract-audio --audio-format mp3 " \
        yta-opus="yt-dlp --extract-audio --audio-format opus " \
        yta-vorbis="yt-dlp --extract-audio --audio-format vorbis " \
        yta-wav="yt-dlp --extract-audio --audio-format wav " \
        ytv-best="yt-dlp -f bestvideo+bestaudio " \
        yt="yt-dlp -f bestvideo+bestaudio " \
        yta="yt-dlp --extract-audio --audio-quality 0 --audio-format opus --add-metadata -o '%(artist)s - %(title)s.%(ext)s'" \
        ytap="yt-dlp --extract-audio --audio-quality 0 --audio-format opus --add-metadata -o '%(playlist)s/%(playlist_index)02d. %(artist)s - %(title)s.%(ext)s'"

# Switch between shells
alias \
        tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'" \
        tozsh="sudo chsh  $USER -s /bin/zsh && echo 'Now log out.'" \
        tofish="sudo chsh $USER -s /bin/fish && echo 'Now log out.'"

# Source shell configs
alias \
        sb="source ~/.bashrc" \
        sz="source ~/.config/zsh/.zshrc" \
        sf="source ~/.config/fish/config.fish"

# Switch between display managers
alias \
        tolightdm="sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm --needed ; sudo systemctl enable lightdm.service -f ; echo 'Lightm is active - reboot now'" \
        tosddm="sudo pacman -S sddm --noconfirm --needed ; sudo systemctl enable sddm.service -f ; echo 'Sddm is active - reboot now'" \
        toly="sudo pacman -S ly --noconfirm --needed ; sudo systemctl enable ly.service -f ; echo 'Ly is active - reboot now'" \
        togdm="sudo pacman -S gdm --noconfirm --needed ; sudo systemctl enable gdm.service -f ; echo 'Gdm is active - reboot now'"

# Common commands that are too long
alias \
        e="$EDITOR" \
        v="vim" \
        ka="killall" \
        xp="xprop WM_CLASS" \
        p="sudo pacman" \
        g="git" \
        s="startx" \
        c="clear" \
        r="ranger"

# root privileges
alias doas="doas --"

# get error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# Merge Xresources
alias merge="xrdb -merge ~/.Xresources"

# bare git repo alias for dotfiles
alias dot="/usr/bin/git --git-dir=$HOME/.local/share/dotfiles --work-tree=$HOME"

# the terminal rickroll
alias rr="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"

# Make multiple directorys at once
alias mkdir="mkdir -p"

# Copy the last command
alias lc='echo "$(history | head -2 | sed "s/  [0-9]*  //;2d")" > /tmp/cmdoutput && cat /tmp/cmdoutput | xsel -b && notify-send "Terminal" "Last Command Copied"'

# Userlist
alias userlist="< /etc/passwd | column -t -s : | sort"

# Update grub config
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

# Check for new fonts
alias update-fc="sudo fc-cache -fv"

# Hardware information
alias hw="hwinfo --short"

# Check audio server
alias audio="pactl info | grep 'Server Name'"

# Largest files in directory
alias ducks="du -cks * | sort -rn | head"

# Logout
alias logout="pkill -KILL -u $USER"

# Remove all latex temp files
alias latexclear="rm -f *.aux; rm -f *.log; rm -f *.toc"

# clang compiler
alias clangg="clang++ --std=c++20 -O3 -fsanitize=address,undefined -Wall -Wextra -Werror"

# Short command for pushing configs
cfg() { config add "$1"; config commit -m "$2" ; }

alias hst="history 1 -1 | cut -c 8- | sort | uniq | fzf | tr -d '\n' | xclip -sel c"
alias ec="editconfig --fzf"

#alias sxiv="devour sxiv"
#alias mpv="devour mpv"
#alias zathura="devour zathura"
#alias lowriter="devour lowriter"
#alias neofetch="neofetch --ascii_distro arch"
# Fast cds
alias sc="cd ~/.local/bin               && ls -a --color=always"
alias bm="vim ~/.local/share/bookmarks"
alias qa="~/.config/qtile/autostart.sh"
alias sl="cd ~/.config/suckless         && ls -a --color=always"
alias src="cd ~/.local/src              && ls -a --color=always"
alias cf="cd ~/.config                  && ls -a --color=always"


alias o="xdg-open"
alias ss="sudo systemctl"
alias cal="cal -m"
# close aria2 after download
alias aria2c="aria2c --seed-time=0"
alias y="xclip -sel c"
alias P="xclip -o"
alias ex="extract"
alias pyenv="[ ! -d venv ] && python -m venv venv ; . ./venv/bin/activate ; pip install -U pip"
alias pyreq="[ ! -f requirements.txt ] && echo 'requirements.txt not found' && return 1 ; [ -d venv ] && ./venv/bin/pip install -r requirements.txt -U pip || echo 'venv no found' && return 1"
alias pygenreq="[ -d venv ] && ./venv/bin/pip freeze > requirements.txt"
alias pyall="pyenv && pyreq"

# Backup
bak() { cp -rf "$1" "$1.bak" ; }

shrinkpdf() {
gs  -q -dNOPAUSE -dBATCH -dSAFER \
    -sDEVICE=pdfwrite \
    -dCompatibilityLevel=1.4 \
    -dPDFSETTINGS=/screen \
    -dEmbedAllFonts=true \
    -dSubsetFonts=true \
    -dColorImageDownsampleType=/Bicubic \
    -dColorImageResolution=150 \
    -dGrayImageDownsampleType=/Bicubic \
    -dGrayImageResolution=150 \
    -dMonoImageDownsampleType=/Bicubic \
    -dMonoImageResolution=150 \
    -sOutputFile="compressed-$1" \
     "$1"
mv "compressed-$1" "$1" -i
}

fcd() {
    dir="$(find "$HOME" -type d | fzf)"
    [ -z "$dir" ] && cd "$dir" || return
}

ren() { perl-rename 's/$1//g' -- * ; }

countdown() {
    n=$1
    while [ "$n" -gt 0 ]; do
        echo "$n" | figlet -c | lolcat && sleep 1
        n=$((n-1))
    done
}
