#!/bin/sh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# change vim to neovim if installed
[ -x "$(command -v nvim)" ] && alias vim="nvim"

# Sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="sudo $command"
done; unset command

enable() { [ -d "/etc/runit/sv/$1" ] && sudo ln -s "/etc/runit/sv/$1" /run/runit/service/ ;}
disable() { [ -L "/run/runit/service/$1" ] && sudo unlink "/run/runit/service/$1" ;}

bak() { cp -rf "$1" "$1.bak" ;}
hst() { [ -f "$HISTFILE" ] && awk '!seen[$0]++' "$HISTFILE" | tac | fzf | tr -d '\n' | xclip -sel c ;}
last() { [ -f "$HISTFILE" ] && tail -n2 "$HISTFILE" | head -n1 | tr -d '\n' | xclip -sel c ;}

venv() {
    venv="${1:-venv}"
    [ -d "$venv" ] && . "$venv/bin/activate" && return 0
    python -m venv "$venv"
    . "$venv/bin/activate" || return 1
    pip install -U pip
    [ -f "requirements.txt" ] && pip install -r "requirements.txt"
}

se() { $EDITOR ~/.local/bin/"$(find ~/.local/bin/ -type f -printf '%P\n' | fzf)" ;}

# Verbosity and sane flags
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias mkdir="mkdir -pv"
alias rsync="rsync -vrPlu"
alias bc="bc -lq"
alias ffmpeg="ffmpeg -hide_banner"
alias yt="yt-dlp -i --add-metadata -f bestvideo+bestaudio"
alias yta="yt-dlp -i --add-metadata --extract-audio --audio-quality=0 --audio-format=opus"
alias ytap="yta --parse-metadata='playlist_index:%(track_number)s'"
alias sudo="sudo "  # make sudo work with aliases
alias cal="cal -m"

# Colorize output when possible
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias ip="ip --color=auto"
alias ccat="highlight --out-format=ansi"

# Abbreviations for common commands that are too long
alias p="pacman"
alias g="git"
alias ka="killall"
alias e="$EDITOR"
alias v="$EDITOR"
alias o="xdg-open"
alias y="xclip -sel c"
alias z="zathura"

# Other aliases
alias psmem="ps auxf | sort -nr -k 4 | head"
alias pscpu="ps auxf | sort -nr -k 3 | head"
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias xp="xprop WM_CLASS"
alias gu="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias ce="editconfig --fzf"
alias sr="rsync ~/.local/src/site/* root@thirtysix.pw:/var/www/thirtysix"
alias ref="shortcuts ; source $HOME/.config/shortcuts ; source $HOME/.config/nameddirs"
