#! /bin/bash

# Autostart
lxsession &
nitrogen --restore &
pgrep -x xcompmgr > /dev/null || xcompmgr &
sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc || pkill -USR1 -x sxhkd &
dunst --config $HOME/.config/dunst/dunstrc &
$HOME/.config/polybar/bsplaunch.sh &
setxkbmap -model pc104 -layout us,ru -variant ,, -option grp:alt_shift_toggle

# Workspaces
bspc monitor HDMI-1 -d dev www chat sys vbox mus vid doc pass

# Configuration
bspc config border_width                  2
bspc config window_gap                    12
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Colors
bspc config normal_border_color		      "#44475a"
bspc config active_border_color	          "#44475a"
bspc config focused_border_color	      "#bd93f9"
bspc config presel_feedback_color	      "#bd93f9"
bspc config urgent_border_color 	      "#ff5555"

# Window Rules
# bspc rule -r "*"
bspc rule -a "TelegramDesktop" desktop="^3"
bspc rule -a "VirtualBox Manager" desktop="^5"
bspc rule -a "Virt-manager" desktop="^5"
bspc rule -a "obs" desktop="^7"
bspc rule -a "KeePassXC" desktop="^9"
bspc rule -a "scratchpad" state=floating
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "qt5ct" state=floating
bspc rule -a "Yad" state=floating
bspc rule -a "Galculator" state=floating
bspc rule -a "GParted" state=floating
bspc rule -a "Lxappearance" state=floating
bspc rule -a "Xfburn" state=floating
bspc rule -a "Nitrogen" state=floating
bspc rule -a "Gpick" state=floating
bspc rule -a "bottles" state=floating
bspc rule -a "Com.github.rajsolai.textsnatcher" state=floating
bspc rule -a "Kvantum Manager" state=floating
